# General
lang:        el
title:       Οικογένεια Γκαράνη
description: Πληροφορίες και ιστορίες σχετικές με την οικογένεια Γκαράνη.
url:         https://nyg.github.io
baseurl:     /garanis.family

# Index page
show_excerpts: true

# Theme
theme: minima
minima:
  date_format: "%d/%m/%Y"

# Plugins
plugins:
  - jekyll-feed
