baseURL = 'https://garanis.family/'
languageCode = 'el-gr'
defaultContentLanguage = 'el'
title = 'Οικογένεια Γκαράνη'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[permalinks]
pages = "/:contentbasename/"

[params]
mainSections = ["posts"]
custom_css = ["css/custom.css"]
cover_dimming_class = "bg-transparent"
