baseURL = 'https://nyg.github.io/garanis.family/'
languageCode = 'el-gr'
title = 'Οικογένεια Γκαράνη'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[permalinks]
pages = "/:contentbasename/"

[params]
mainSections = ["posts"]
